// flow-typed signature: 917915f322db5a4a5db165cd9cd18eff
// flow-typed version: <<STUB>>/@lugia/lugia-web_v1.0.43-11/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/lugia-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@lugia/lugia-web" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@lugia/lugia-web/dist/affix/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/affix/affix" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/affix/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/affix/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/alert/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/alert/alert" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/alert/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/alert/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/align/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/align/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/amountinput/__tests__/amountUtils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/amountinput/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/amountinput/amountUtils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/amountinput/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/amountinput/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/autocomplete/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/autocomplete/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/autocomplete/emailDemo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/autocomplete/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/avatar/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/avatar/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/avatar/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/back-top/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/back-top/back-top" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/back-top/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/back-top/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/badge/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/badge/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/badge/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/badge/numberturn/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/breadcrumb/__tests__/breadcrumb.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/breadcrumb/breadcrumb" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/breadcrumb/breadcrumbItem" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/breadcrumb/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/breadcrumb/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/button/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/button/button-group" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/button/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/button/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/cascader/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/cascader/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/check-button/__tests__/check-button.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/check-button/button" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/check-button/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/_tests_/CheckBox.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/_tests_/CheckBoxGroup.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/checkAll" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/checkbox-group" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/checkbox" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/checkbox/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/collapse/__tests__/collapse.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/collapse/collapse" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/collapse/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/collapse/panel" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/DelayHoc.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/FormFieldWidgetSupport.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/MaskBox.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/Math.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/ObjectUtils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/ShortKeyBoard.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/StringUtils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/ThemeProvider.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/ThemeUtils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/translateData.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/__tests__/VisibleBox.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/circleUtils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/DelayHoc" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/FormFieldWidgetSupport" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/getRequestAnimationFrame" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/KeyBoardEventAdaptor" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/MaskBox" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/Math" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/MouseEventAdaptor" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/ObjectUtils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/openAnimation" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/PlaceContainer" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/QueryInput" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/QueryInputContainer" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/selectFunction" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/shirm" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/ShortKeyBoard" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/StringUtils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/ThemeUtils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/translateData" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/common/VisibleBox" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/consts/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/consts/KeyBoard" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/consts/KeyCode" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/consts/props" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/__test__/stateColor.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/__test__/unit.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/__test__/utilsColor.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/affix" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/alert" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/aside" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/autocomplete" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/avatar" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/back-top" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/badge" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/block" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/breadcrumb" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/button" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/check-button" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/checkbox" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/col" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/collapse" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/component-iconwrap" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/divider" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/dropmenubutton" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/input" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/inputtag" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/layout" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/menu" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/message" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/modal" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/notification" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/number-input" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/panel" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/progress-circle" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/progress-line" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/queryInput" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/radio" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/row" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/scroller" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/select" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/stateColor" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/steps" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/table" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/tabs" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/tag" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/tooltip" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/tree" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/units" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/css/utilsColor" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/__test__/date.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Date" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/DateInput" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/DatePanel" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/DatePicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/FacePanel" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/getDerived" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Head" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Month" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/MonthPicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Range" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/RangeInput" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/RangePicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/SingleRange" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/styled" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/styleTime" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/SwitchPanel" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Time" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/TimeInput" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/TimePicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/TimeSiglePicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/week" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/WeekPicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Weeks" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/WeeksPicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/Year" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/date-picker/YearPicker" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/divider/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/divider/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/divider/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/dropmenu/__tests__/dropmenuButton.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/dropmenu/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/dropmenu/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/dropmenu/dropmenuButton" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/dropmenu/dropmenuButtondemo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/dropmenu/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/grid/__tests__/col.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/grid/__tests__/row.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/grid/col" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/grid/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/grid/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/grid/row" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/AddIcon" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/CheckIcon" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/ClearIcon" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/PullIcon" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/RefreshIcon" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/icon/SearchIcon" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/input/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/input/__tests__/InputTestUtils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/input/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/input/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/__test__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/FontItem" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/Item" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/ItemOption" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/ItemTag" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/inputtag/MoreItem" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/__tests__/aside.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/__tests__/layout.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/aside" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/block" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/content" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/layout/layout" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/loading/__tests__/loading.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/loading/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/loading/loading" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/loading/styled" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/__tests__/item.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/demo-data" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/item" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/menu/test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/__tests__/icon-component.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/create-message" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/icon-content" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/message/message" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/modal/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/modal/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/modal/fncmodal" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/modal/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/modal/modal" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/modal/quickcall" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/notification/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/notification/create" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/notification/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/notification/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/notification/notification" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/numberinput/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/numberinput/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/numberinput/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/progress/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/progress/circle" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/progress/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/progress/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/progress/line" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/progress/progress" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/radio/_tests_/Radio-group.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/radio/_tests_/Radio.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/radio/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/radio/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/radio/radio-group" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/radio/radio" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/scroller/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/scroller/__tests__/ThrottleScroller.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/scroller/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/scroller/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/scroller/support" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/scroller/ThrottleScroller" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/select/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/select/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/select/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/slider/__test__/slider.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/slider/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/slider/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/slider/slider_public_color" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/slider/slider" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/slider/styled" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/steps/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/steps/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/steps/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/steps/step" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/switch/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/switch/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/switch/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/switch/styled" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/switch/switch" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/table/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/table/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/table/table" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/__tests__/tabpane.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/__tests__/utils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/tabcontent" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/tabpane" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tabs/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tag/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tag/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tag/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/theme-provider/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/theme-provider/index" {
  declare module.exports: any;
}
declare module "@lugia/lugia-web/dist/theme-provider" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/theme/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/theme/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/theme/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tooltip/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tooltip/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tooltip/ErrorTip" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tooltip/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree-select/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree-select/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree-select/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/__tests__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/__tests__/utils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/rc-tree/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/rc-tree/Tree" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/rc-tree/TreeNode" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/rc-tree/util" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/ThrottleTree" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/tree/version" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/__tests__/ContentBox.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/__tests__/Popup.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/__tests__/PopupInner.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/ContentBox" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/demo" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/Popup" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/trigger/PopupInner" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/utils/__test__/index.test" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/dist/utils/index" {
  declare module.exports: any;
}

declare module "@lugia/lugia-web/interface/lugia-web.flow" {
  declare module.exports: any;
}

// Filename aliases
declare module "@lugia/lugia-web/dist/affix/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/affix/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/affix/affix.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/affix/affix">;
}
declare module "@lugia/lugia-web/dist/affix/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/affix/demo">;
}
declare module "@lugia/lugia-web/dist/affix/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/affix/index">;
}
declare module "@lugia/lugia-web/dist/alert/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/alert/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/alert/alert.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/alert/alert">;
}
declare module "@lugia/lugia-web/dist/alert/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/alert/demo">;
}
declare module "@lugia/lugia-web/dist/alert/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/alert/index">;
}
declare module "@lugia/lugia-web/dist/align/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/align/demo">;
}
declare module "@lugia/lugia-web/dist/align/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/align/index">;
}
declare module "@lugia/lugia-web/dist/amountinput/__tests__/amountUtils.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/amountinput/__tests__/amountUtils.test"
  >;
}
declare module "@lugia/lugia-web/dist/amountinput/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/amountinput/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/amountinput/amountUtils.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/amountinput/amountUtils"
  >;
}
declare module "@lugia/lugia-web/dist/amountinput/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/amountinput/demo">;
}
declare module "@lugia/lugia-web/dist/amountinput/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/amountinput/index">;
}
declare module "@lugia/lugia-web/dist/autocomplete/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/autocomplete/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/autocomplete/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/autocomplete/demo">;
}
declare module "@lugia/lugia-web/dist/autocomplete/emailDemo.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/autocomplete/emailDemo"
  >;
}
declare module "@lugia/lugia-web/dist/autocomplete/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/autocomplete/index">;
}
declare module "@lugia/lugia-web/dist/avatar/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/avatar/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/avatar/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/avatar/demo">;
}
declare module "@lugia/lugia-web/dist/avatar/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/avatar/index">;
}
declare module "@lugia/lugia-web/dist/back-top/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/back-top/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/back-top/back-top.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/back-top/back-top">;
}
declare module "@lugia/lugia-web/dist/back-top/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/back-top/demo">;
}
declare module "@lugia/lugia-web/dist/back-top/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/back-top/index">;
}
declare module "@lugia/lugia-web/dist/badge/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/badge/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/badge/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/badge/demo">;
}
declare module "@lugia/lugia-web/dist/badge/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/badge/index">;
}
declare module "@lugia/lugia-web/dist/badge/numberturn/index.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/badge/numberturn/index"
  >;
}
declare module "@lugia/lugia-web/dist/breadcrumb/__tests__/breadcrumb.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/breadcrumb/__tests__/breadcrumb.test"
  >;
}
declare module "@lugia/lugia-web/dist/breadcrumb/breadcrumb.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/breadcrumb/breadcrumb"
  >;
}
declare module "@lugia/lugia-web/dist/breadcrumb/breadcrumbItem.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/breadcrumb/breadcrumbItem"
  >;
}
declare module "@lugia/lugia-web/dist/breadcrumb/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/breadcrumb/demo">;
}
declare module "@lugia/lugia-web/dist/breadcrumb/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/breadcrumb/index">;
}
declare module "@lugia/lugia-web/dist/button/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/button/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/button/button-group.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/button/button-group">;
}
declare module "@lugia/lugia-web/dist/button/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/button/demo">;
}
declare module "@lugia/lugia-web/dist/button/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/button/index">;
}
declare module "@lugia/lugia-web/dist/cascader/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/cascader/demo">;
}
declare module "@lugia/lugia-web/dist/cascader/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/cascader/index">;
}
declare module "@lugia/lugia-web/dist/check-button/__tests__/check-button.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/check-button/__tests__/check-button.test"
  >;
}
declare module "@lugia/lugia-web/dist/check-button/button.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/check-button/button">;
}
declare module "@lugia/lugia-web/dist/check-button/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/check-button/demo">;
}
declare module "@lugia/lugia-web/dist/checkbox/_tests_/CheckBox.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/checkbox/_tests_/CheckBox.test"
  >;
}
declare module "@lugia/lugia-web/dist/checkbox/_tests_/CheckBoxGroup.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/checkbox/_tests_/CheckBoxGroup.test"
  >;
}
declare module "@lugia/lugia-web/dist/checkbox/checkAll.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/checkbox/checkAll">;
}
declare module "@lugia/lugia-web/dist/checkbox/checkbox-group.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/checkbox/checkbox-group"
  >;
}
declare module "@lugia/lugia-web/dist/checkbox/checkbox.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/checkbox/checkbox">;
}
declare module "@lugia/lugia-web/dist/checkbox/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/checkbox/demo">;
}
declare module "@lugia/lugia-web/dist/checkbox/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/checkbox/index">;
}
declare module "@lugia/lugia-web/dist/collapse/__tests__/collapse.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/collapse/__tests__/collapse.test"
  >;
}
declare module "@lugia/lugia-web/dist/collapse/collapse.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/collapse/collapse">;
}
declare module "@lugia/lugia-web/dist/collapse/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/collapse/demo">;
}
declare module "@lugia/lugia-web/dist/collapse/panel.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/collapse/panel">;
}
declare module "@lugia/lugia-web/dist/common/__tests__/DelayHoc.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/DelayHoc.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/FormFieldWidgetSupport.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/FormFieldWidgetSupport.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/MaskBox.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/MaskBox.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/Math.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/Math.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/ObjectUtils.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/ObjectUtils.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/ShortKeyBoard.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/ShortKeyBoard.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/StringUtils.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/StringUtils.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/ThemeProvider.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/ThemeProvider.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/ThemeUtils.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/ThemeUtils.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/translateData.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/translateData.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/__tests__/VisibleBox.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/__tests__/VisibleBox.test"
  >;
}
declare module "@lugia/lugia-web/dist/common/circleUtils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/circleUtils">;
}
declare module "@lugia/lugia-web/dist/common/DelayHoc.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/DelayHoc">;
}
declare module "@lugia/lugia-web/dist/common/FormFieldWidgetSupport.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/FormFieldWidgetSupport"
  >;
}
declare module "@lugia/lugia-web/dist/common/getRequestAnimationFrame.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/getRequestAnimationFrame"
  >;
}
declare module "@lugia/lugia-web/dist/common/KeyBoardEventAdaptor.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/KeyBoardEventAdaptor"
  >;
}
declare module "@lugia/lugia-web/dist/common/MaskBox.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/MaskBox">;
}
declare module "@lugia/lugia-web/dist/common/Math.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/Math">;
}
declare module "@lugia/lugia-web/dist/common/MouseEventAdaptor.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/MouseEventAdaptor"
  >;
}
declare module "@lugia/lugia-web/dist/common/ObjectUtils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/ObjectUtils">;
}
declare module "@lugia/lugia-web/dist/common/openAnimation.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/openAnimation"
  >;
}
declare module "@lugia/lugia-web/dist/common/PlaceContainer.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/PlaceContainer"
  >;
}
declare module "@lugia/lugia-web/dist/common/QueryInput.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/QueryInput">;
}
declare module "@lugia/lugia-web/dist/common/QueryInputContainer.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/QueryInputContainer"
  >;
}
declare module "@lugia/lugia-web/dist/common/selectFunction.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/selectFunction"
  >;
}
declare module "@lugia/lugia-web/dist/common/shirm.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/shirm">;
}
declare module "@lugia/lugia-web/dist/common/ShortKeyBoard.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/ShortKeyBoard"
  >;
}
declare module "@lugia/lugia-web/dist/common/StringUtils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/StringUtils">;
}
declare module "@lugia/lugia-web/dist/common/ThemeUtils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/ThemeUtils">;
}
declare module "@lugia/lugia-web/dist/common/translateData.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/common/translateData"
  >;
}
declare module "@lugia/lugia-web/dist/common/VisibleBox.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/common/VisibleBox">;
}
declare module "@lugia/lugia-web/dist/consts/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/consts/index">;
}
declare module "@lugia/lugia-web/dist/consts/KeyBoard.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/consts/KeyBoard">;
}
declare module "@lugia/lugia-web/dist/consts/KeyCode.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/consts/KeyCode">;
}
declare module "@lugia/lugia-web/dist/consts/props.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/consts/props">;
}
declare module "@lugia/lugia-web/dist/css/__test__/stateColor.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/css/__test__/stateColor.test"
  >;
}
declare module "@lugia/lugia-web/dist/css/__test__/unit.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/css/__test__/unit.test"
  >;
}
declare module "@lugia/lugia-web/dist/css/__test__/utilsColor.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/css/__test__/utilsColor.test"
  >;
}
declare module "@lugia/lugia-web/dist/css/affix.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/affix">;
}
declare module "@lugia/lugia-web/dist/css/alert.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/alert">;
}
declare module "@lugia/lugia-web/dist/css/aside.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/aside">;
}
declare module "@lugia/lugia-web/dist/css/autocomplete.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/autocomplete">;
}
declare module "@lugia/lugia-web/dist/css/avatar.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/avatar">;
}
declare module "@lugia/lugia-web/dist/css/back-top.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/back-top">;
}
declare module "@lugia/lugia-web/dist/css/badge.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/badge">;
}
declare module "@lugia/lugia-web/dist/css/block.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/block">;
}
declare module "@lugia/lugia-web/dist/css/breadcrumb.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/breadcrumb">;
}
declare module "@lugia/lugia-web/dist/css/button.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/button">;
}
declare module "@lugia/lugia-web/dist/css/check-button.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/check-button">;
}
declare module "@lugia/lugia-web/dist/css/checkbox.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/checkbox">;
}
declare module "@lugia/lugia-web/dist/css/col.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/col">;
}
declare module "@lugia/lugia-web/dist/css/collapse.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/collapse">;
}
declare module "@lugia/lugia-web/dist/css/component-iconwrap.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/css/component-iconwrap"
  >;
}
declare module "@lugia/lugia-web/dist/css/divider.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/divider">;
}
declare module "@lugia/lugia-web/dist/css/dropmenubutton.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/dropmenubutton">;
}
declare module "@lugia/lugia-web/dist/css/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/index">;
}
declare module "@lugia/lugia-web/dist/css/input.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/input">;
}
declare module "@lugia/lugia-web/dist/css/inputtag.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/inputtag">;
}
declare module "@lugia/lugia-web/dist/css/layout.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/layout">;
}
declare module "@lugia/lugia-web/dist/css/menu.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/menu">;
}
declare module "@lugia/lugia-web/dist/css/message.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/message">;
}
declare module "@lugia/lugia-web/dist/css/modal.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/modal">;
}
declare module "@lugia/lugia-web/dist/css/notification.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/notification">;
}
declare module "@lugia/lugia-web/dist/css/number-input.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/number-input">;
}
declare module "@lugia/lugia-web/dist/css/panel.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/panel">;
}
declare module "@lugia/lugia-web/dist/css/progress-circle.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/progress-circle">;
}
declare module "@lugia/lugia-web/dist/css/progress-line.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/progress-line">;
}
declare module "@lugia/lugia-web/dist/css/queryInput.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/queryInput">;
}
declare module "@lugia/lugia-web/dist/css/radio.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/radio">;
}
declare module "@lugia/lugia-web/dist/css/row.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/row">;
}
declare module "@lugia/lugia-web/dist/css/scroller.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/scroller">;
}
declare module "@lugia/lugia-web/dist/css/select.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/select">;
}
declare module "@lugia/lugia-web/dist/css/stateColor.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/stateColor">;
}
declare module "@lugia/lugia-web/dist/css/steps.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/steps">;
}
declare module "@lugia/lugia-web/dist/css/table.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/table">;
}
declare module "@lugia/lugia-web/dist/css/tabs.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/tabs">;
}
declare module "@lugia/lugia-web/dist/css/tag.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/tag">;
}
declare module "@lugia/lugia-web/dist/css/tooltip.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/tooltip">;
}
declare module "@lugia/lugia-web/dist/css/tree.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/tree">;
}
declare module "@lugia/lugia-web/dist/css/units.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/units">;
}
declare module "@lugia/lugia-web/dist/css/utilsColor.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/css/utilsColor">;
}
declare module "@lugia/lugia-web/dist/date-picker/__test__/date.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/__test__/date.test"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/Date.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Date">;
}
declare module "@lugia/lugia-web/dist/date-picker/DateInput.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/DateInput"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/DatePanel.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/DatePanel"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/DatePicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/DatePicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/demo">;
}
declare module "@lugia/lugia-web/dist/date-picker/FacePanel.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/FacePanel"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/getDerived.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/getDerived"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/Head.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Head">;
}
declare module "@lugia/lugia-web/dist/date-picker/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/index">;
}
declare module "@lugia/lugia-web/dist/date-picker/Month.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Month">;
}
declare module "@lugia/lugia-web/dist/date-picker/MonthPicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/MonthPicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/Range.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Range">;
}
declare module "@lugia/lugia-web/dist/date-picker/RangeInput.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/RangeInput"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/RangePicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/RangePicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/SingleRange.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/SingleRange"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/styled.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/styled">;
}
declare module "@lugia/lugia-web/dist/date-picker/styleTime.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/styleTime"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/SwitchPanel.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/SwitchPanel"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/Time.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Time">;
}
declare module "@lugia/lugia-web/dist/date-picker/TimeInput.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/TimeInput"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/TimePicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/TimePicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/TimeSiglePicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/TimeSiglePicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/utils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/utils">;
}
declare module "@lugia/lugia-web/dist/date-picker/week.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/week">;
}
declare module "@lugia/lugia-web/dist/date-picker/WeekPicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/WeekPicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/Weeks.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Weeks">;
}
declare module "@lugia/lugia-web/dist/date-picker/WeeksPicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/WeeksPicker"
  >;
}
declare module "@lugia/lugia-web/dist/date-picker/Year.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/date-picker/Year">;
}
declare module "@lugia/lugia-web/dist/date-picker/YearPicker.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/date-picker/YearPicker"
  >;
}
declare module "@lugia/lugia-web/dist/divider/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/divider/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/divider/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/divider/demo">;
}
declare module "@lugia/lugia-web/dist/divider/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/divider/index">;
}
declare module "@lugia/lugia-web/dist/dropmenu/__tests__/dropmenuButton.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/dropmenu/__tests__/dropmenuButton.test"
  >;
}
declare module "@lugia/lugia-web/dist/dropmenu/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/dropmenu/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/dropmenu/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/dropmenu/demo">;
}
declare module "@lugia/lugia-web/dist/dropmenu/dropmenuButton.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/dropmenu/dropmenuButton"
  >;
}
declare module "@lugia/lugia-web/dist/dropmenu/dropmenuButtondemo.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/dropmenu/dropmenuButtondemo"
  >;
}
declare module "@lugia/lugia-web/dist/dropmenu/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/dropmenu/index">;
}
declare module "@lugia/lugia-web/dist/grid/__tests__/col.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/grid/__tests__/col.test"
  >;
}
declare module "@lugia/lugia-web/dist/grid/__tests__/row.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/grid/__tests__/row.test"
  >;
}
declare module "@lugia/lugia-web/dist/grid/col.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/grid/col">;
}
declare module "@lugia/lugia-web/dist/grid/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/grid/demo">;
}
declare module "@lugia/lugia-web/dist/grid/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/grid/index">;
}
declare module "@lugia/lugia-web/dist/grid/row.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/grid/row">;
}
declare module "@lugia/lugia-web/dist/icon/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/icon/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/icon/AddIcon.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/AddIcon">;
}
declare module "@lugia/lugia-web/dist/icon/CheckIcon.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/CheckIcon">;
}
declare module "@lugia/lugia-web/dist/icon/ClearIcon.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/ClearIcon">;
}
declare module "@lugia/lugia-web/dist/icon/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/demo">;
}
declare module "@lugia/lugia-web/dist/icon/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/index">;
}
declare module "@lugia/lugia-web/dist/icon/PullIcon.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/PullIcon">;
}
declare module "@lugia/lugia-web/dist/icon/RefreshIcon.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/RefreshIcon">;
}
declare module "@lugia/lugia-web/dist/icon/SearchIcon.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/icon/SearchIcon">;
}
declare module "@lugia/lugia-web/dist/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/index">;
}
declare module "@lugia/lugia-web/dist/input/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/input/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/input/__tests__/InputTestUtils.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/input/__tests__/InputTestUtils"
  >;
}
declare module "@lugia/lugia-web/dist/input/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/input/demo">;
}
declare module "@lugia/lugia-web/dist/input/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/input/index">;
}
declare module "@lugia/lugia-web/dist/inputtag/__test__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/inputtag/__test__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/inputtag/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/demo">;
}
declare module "@lugia/lugia-web/dist/inputtag/FontItem.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/FontItem">;
}
declare module "@lugia/lugia-web/dist/inputtag/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/index">;
}
declare module "@lugia/lugia-web/dist/inputtag/Item.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/Item">;
}
declare module "@lugia/lugia-web/dist/inputtag/ItemOption.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/ItemOption">;
}
declare module "@lugia/lugia-web/dist/inputtag/ItemTag.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/ItemTag">;
}
declare module "@lugia/lugia-web/dist/inputtag/MoreItem.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/inputtag/MoreItem">;
}
declare module "@lugia/lugia-web/dist/layout/__tests__/aside.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/layout/__tests__/aside.test"
  >;
}
declare module "@lugia/lugia-web/dist/layout/__tests__/layout.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/layout/__tests__/layout.test"
  >;
}
declare module "@lugia/lugia-web/dist/layout/aside.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/layout/aside">;
}
declare module "@lugia/lugia-web/dist/layout/block.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/layout/block">;
}
declare module "@lugia/lugia-web/dist/layout/content.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/layout/content">;
}
declare module "@lugia/lugia-web/dist/layout/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/layout/demo">;
}
declare module "@lugia/lugia-web/dist/layout/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/layout/index">;
}
declare module "@lugia/lugia-web/dist/layout/layout.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/layout/layout">;
}
declare module "@lugia/lugia-web/dist/loading/__tests__/loading.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/loading/__tests__/loading.test"
  >;
}
declare module "@lugia/lugia-web/dist/loading/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/loading/demo">;
}
declare module "@lugia/lugia-web/dist/loading/loading.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/loading/loading">;
}
declare module "@lugia/lugia-web/dist/loading/styled.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/loading/styled">;
}
declare module "@lugia/lugia-web/dist/menu/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/menu/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/menu/__tests__/item.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/menu/__tests__/item.test"
  >;
}
declare module "@lugia/lugia-web/dist/menu/demo-data.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/menu/demo-data">;
}
declare module "@lugia/lugia-web/dist/menu/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/menu/demo">;
}
declare module "@lugia/lugia-web/dist/menu/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/menu/index">;
}
declare module "@lugia/lugia-web/dist/menu/item.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/menu/item">;
}
declare module "@lugia/lugia-web/dist/menu/test.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/menu/test">;
}
declare module "@lugia/lugia-web/dist/message/__tests__/icon-component.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/message/__tests__/icon-component.test"
  >;
}
declare module "@lugia/lugia-web/dist/message/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/message/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/message/create-message.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/message/create-message"
  >;
}
declare module "@lugia/lugia-web/dist/message/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/message/demo">;
}
declare module "@lugia/lugia-web/dist/message/icon-content.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/message/icon-content"
  >;
}
declare module "@lugia/lugia-web/dist/message/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/message/index">;
}
declare module "@lugia/lugia-web/dist/message/message.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/message/message">;
}
declare module "@lugia/lugia-web/dist/modal/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/modal/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/modal/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/modal/demo">;
}
declare module "@lugia/lugia-web/dist/modal/fncmodal.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/modal/fncmodal">;
}
declare module "@lugia/lugia-web/dist/modal/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/modal/index">;
}
declare module "@lugia/lugia-web/dist/modal/modal.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/modal/modal">;
}
declare module "@lugia/lugia-web/dist/modal/quickcall.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/modal/quickcall">;
}
declare module "@lugia/lugia-web/dist/notification/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/notification/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/notification/create.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/notification/create">;
}
declare module "@lugia/lugia-web/dist/notification/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/notification/demo">;
}
declare module "@lugia/lugia-web/dist/notification/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/notification/index">;
}
declare module "@lugia/lugia-web/dist/notification/notification.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/notification/notification"
  >;
}
declare module "@lugia/lugia-web/dist/numberinput/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/numberinput/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/numberinput/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/numberinput/demo">;
}
declare module "@lugia/lugia-web/dist/numberinput/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/numberinput/index">;
}
declare module "@lugia/lugia-web/dist/progress/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/progress/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/progress/circle.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/progress/circle">;
}
declare module "@lugia/lugia-web/dist/progress/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/progress/demo">;
}
declare module "@lugia/lugia-web/dist/progress/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/progress/index">;
}
declare module "@lugia/lugia-web/dist/progress/line.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/progress/line">;
}
declare module "@lugia/lugia-web/dist/progress/progress.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/progress/progress">;
}
declare module "@lugia/lugia-web/dist/radio/_tests_/Radio-group.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/radio/_tests_/Radio-group.test"
  >;
}
declare module "@lugia/lugia-web/dist/radio/_tests_/Radio.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/radio/_tests_/Radio.test"
  >;
}
declare module "@lugia/lugia-web/dist/radio/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/radio/demo">;
}
declare module "@lugia/lugia-web/dist/radio/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/radio/index">;
}
declare module "@lugia/lugia-web/dist/radio/radio-group.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/radio/radio-group">;
}
declare module "@lugia/lugia-web/dist/radio/radio.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/radio/radio">;
}
declare module "@lugia/lugia-web/dist/scroller/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/scroller/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/scroller/__tests__/ThrottleScroller.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/scroller/__tests__/ThrottleScroller.test"
  >;
}
declare module "@lugia/lugia-web/dist/scroller/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/scroller/demo">;
}
declare module "@lugia/lugia-web/dist/scroller/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/scroller/index">;
}
declare module "@lugia/lugia-web/dist/scroller/support.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/scroller/support">;
}
declare module "@lugia/lugia-web/dist/scroller/ThrottleScroller.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/scroller/ThrottleScroller"
  >;
}
declare module "@lugia/lugia-web/dist/select/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/select/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/select/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/select/demo">;
}
declare module "@lugia/lugia-web/dist/select/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/select/index">;
}
declare module "@lugia/lugia-web/dist/slider/__test__/slider.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/slider/__test__/slider.test"
  >;
}
declare module "@lugia/lugia-web/dist/slider/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/slider/demo">;
}
declare module "@lugia/lugia-web/dist/slider/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/slider/index">;
}
declare module "@lugia/lugia-web/dist/slider/slider_public_color.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/slider/slider_public_color"
  >;
}
declare module "@lugia/lugia-web/dist/slider/slider.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/slider/slider">;
}
declare module "@lugia/lugia-web/dist/slider/styled.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/slider/styled">;
}
declare module "@lugia/lugia-web/dist/steps/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/steps/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/steps/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/steps/demo">;
}
declare module "@lugia/lugia-web/dist/steps/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/steps/index">;
}
declare module "@lugia/lugia-web/dist/steps/step.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/steps/step">;
}
declare module "@lugia/lugia-web/dist/switch/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/switch/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/switch/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/switch/demo">;
}
declare module "@lugia/lugia-web/dist/switch/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/switch/index">;
}
declare module "@lugia/lugia-web/dist/switch/styled.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/switch/styled">;
}
declare module "@lugia/lugia-web/dist/switch/switch.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/switch/switch">;
}
declare module "@lugia/lugia-web/dist/table/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/table/demo">;
}
declare module "@lugia/lugia-web/dist/table/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/table/index">;
}
declare module "@lugia/lugia-web/dist/table/table.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/table/table">;
}
declare module "@lugia/lugia-web/dist/tabs/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tabs/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/tabs/__tests__/tabpane.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tabs/__tests__/tabpane.test"
  >;
}
declare module "@lugia/lugia-web/dist/tabs/__tests__/utils.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tabs/__tests__/utils.test"
  >;
}
declare module "@lugia/lugia-web/dist/tabs/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tabs/demo">;
}
declare module "@lugia/lugia-web/dist/tabs/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tabs/index">;
}
declare module "@lugia/lugia-web/dist/tabs/tabcontent.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tabs/tabcontent">;
}
declare module "@lugia/lugia-web/dist/tabs/tabpane.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tabs/tabpane">;
}
declare module "@lugia/lugia-web/dist/tabs/utils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tabs/utils">;
}
declare module "@lugia/lugia-web/dist/tag/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tag/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/tag/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tag/demo">;
}
declare module "@lugia/lugia-web/dist/tag/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tag/index">;
}
declare module "@lugia/lugia-web/dist/theme-provider/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/theme-provider/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/theme-provider/index.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/theme-provider/index"
  >;
}
declare module "@lugia/lugia-web/dist/theme/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/theme/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/theme/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/theme/index">;
}
declare module "@lugia/lugia-web/dist/theme/utils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/theme/utils">;
}
declare module "@lugia/lugia-web/dist/tooltip/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tooltip/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/tooltip/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tooltip/demo">;
}
declare module "@lugia/lugia-web/dist/tooltip/ErrorTip.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tooltip/ErrorTip">;
}
declare module "@lugia/lugia-web/dist/tooltip/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tooltip/index">;
}
declare module "@lugia/lugia-web/dist/tree-select/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tree-select/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/tree-select/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree-select/demo">;
}
declare module "@lugia/lugia-web/dist/tree-select/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree-select/index">;
}
declare module "@lugia/lugia-web/dist/tree/__tests__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tree/__tests__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/tree/__tests__/utils.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tree/__tests__/utils.test"
  >;
}
declare module "@lugia/lugia-web/dist/tree/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/demo">;
}
declare module "@lugia/lugia-web/dist/tree/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/index">;
}
declare module "@lugia/lugia-web/dist/tree/rc-tree/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/rc-tree/index">;
}
declare module "@lugia/lugia-web/dist/tree/rc-tree/Tree.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/rc-tree/Tree">;
}
declare module "@lugia/lugia-web/dist/tree/rc-tree/TreeNode.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/tree/rc-tree/TreeNode"
  >;
}
declare module "@lugia/lugia-web/dist/tree/rc-tree/util.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/rc-tree/util">;
}
declare module "@lugia/lugia-web/dist/tree/ThrottleTree.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/ThrottleTree">;
}
declare module "@lugia/lugia-web/dist/tree/utils.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/utils">;
}
declare module "@lugia/lugia-web/dist/tree/version.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/tree/version">;
}
declare module "@lugia/lugia-web/dist/trigger/__tests__/ContentBox.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/trigger/__tests__/ContentBox.test"
  >;
}
declare module "@lugia/lugia-web/dist/trigger/__tests__/Popup.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/trigger/__tests__/Popup.test"
  >;
}
declare module "@lugia/lugia-web/dist/trigger/__tests__/PopupInner.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/trigger/__tests__/PopupInner.test"
  >;
}
declare module "@lugia/lugia-web/dist/trigger/ContentBox.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/trigger/ContentBox">;
}
declare module "@lugia/lugia-web/dist/trigger/demo.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/trigger/demo">;
}
declare module "@lugia/lugia-web/dist/trigger/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/trigger/index">;
}
declare module "@lugia/lugia-web/dist/trigger/Popup.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/trigger/Popup">;
}
declare module "@lugia/lugia-web/dist/trigger/PopupInner.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/trigger/PopupInner">;
}
declare module "@lugia/lugia-web/dist/utils/__test__/index.test.js" {
  declare module.exports: $Exports<
    "@lugia/lugia-web/dist/utils/__test__/index.test"
  >;
}
declare module "@lugia/lugia-web/dist/utils/index.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/dist/utils/index">;
}
declare module "@lugia/lugia-web/interface/lugia-web.flow.js" {
  declare module.exports: $Exports<"@lugia/lugia-web/interface/lugia-web.flow">;
}
