// flow-typed signature: 22965f44ae2a0374f855246be68bd7a5
// flow-typed version: <<STUB>>/@lugia/lugiax-router_v^1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/lugiax-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@lugia/lugiax-router" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@lugia/lugiax-router/flow-typed/npm/@lugia/lugiax_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/@lugia/lugiax-core_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/@lugia/react-test-utils_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/babel-jest_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/babel-preset-react-app_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/connected-react-router_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/enzyme_v3.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/enzyme-adapter-react-16_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/flow-bin_v0.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/history_v4.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/history_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/hoist-non-react-statics_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/jest_v20.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/ramda_v0.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/react-dev-utils_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/react-loadable_v5.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/react-redux_v5.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/react-router_v4.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/react-test-renderer_v16.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/flow-typed/npm/styled-components_v3.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/interface/lugiax-router.flow" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/lib/go" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/lib/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/lib/Link" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/lib/Loading" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/lib/router" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/access/NotAccess" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/header/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/todo/components/InputTask" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/todo/components/List" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/todo/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/todo/models/todo" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/components/Button" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/components/History" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/components/Message" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/components/NowTimer" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/components/Timer" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/models/pageload" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/models/tomato" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/pages/history" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/pages/now" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/demo/tomato/pages/PageLoad" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/src/test/router.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/target/interface/lugiax-router.flow" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/target/lib/go" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/target/lib/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/target/lib/Link" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/target/lib/Loading" {
  declare module.exports: any;
}

declare module "@lugia/lugiax-router/target/lib/router" {
  declare module.exports: any;
}

// Filename aliases
declare module "@lugia/lugiax-router/flow-typed/npm/@lugia/lugiax_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/@lugia/lugiax_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/@lugia/lugiax-core_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/@lugia/lugiax-core_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/@lugia/react-test-utils_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/@lugia/react-test-utils_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/babel-jest_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/babel-jest_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/babel-preset-react-app_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/babel-preset-react-app_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/connected-react-router_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/connected-react-router_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/enzyme_v3.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/enzyme_v3.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/enzyme-adapter-react-16_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/flow-bin_v0.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/flow-bin_v0.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/history_v4.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/history_v4.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/history_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/history_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/hoist-non-react-statics_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/hoist-non-react-statics_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/jest_v20.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/jest_v20.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/ramda_v0.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/ramda_v0.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/react-dev-utils_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/react-dev-utils_vx.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/react-loadable_v5.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/react-loadable_v5.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/react-redux_v5.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/react-redux_v5.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/react-router_v4.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/react-router_v4.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/react-test-renderer_v16.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/react-test-renderer_v16.x.x"
  >;
}
declare module "@lugia/lugiax-router/flow-typed/npm/styled-components_v3.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/flow-typed/npm/styled-components_v3.x.x"
  >;
}
declare module "@lugia/lugiax-router/src/interface/lugiax-router.flow.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/interface/lugiax-router.flow"
  >;
}
declare module "@lugia/lugiax-router/src/lib/go.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/lib/go">;
}
declare module "@lugia/lugiax-router/src/lib/index.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/lib/index">;
}
declare module "@lugia/lugiax-router/src/lib/Link.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/lib/Link">;
}
declare module "@lugia/lugiax-router/src/lib/Loading.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/lib/Loading">;
}
declare module "@lugia/lugiax-router/src/lib/router.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/lib/router">;
}
declare module "@lugia/lugiax-router/src/test/demo/access/NotAccess.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/access/NotAccess"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/header/index.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/header/index"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/index.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/test/demo/index">;
}
declare module "@lugia/lugiax-router/src/test/demo/todo/components/InputTask.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/todo/components/InputTask"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/todo/components/List.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/todo/components/List"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/todo/index.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/todo/index"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/todo/models/todo.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/todo/models/todo"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/components/Button.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/components/Button"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/components/History.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/components/History"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/components/Message.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/components/Message"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/components/NowTimer.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/components/NowTimer"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/components/Timer.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/components/Timer"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/index.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/index"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/models/pageload.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/models/pageload"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/models/tomato.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/models/tomato"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/pages/history.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/pages/history"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/pages/now.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/pages/now"
  >;
}
declare module "@lugia/lugiax-router/src/test/demo/tomato/pages/PageLoad.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/src/test/demo/tomato/pages/PageLoad"
  >;
}
declare module "@lugia/lugiax-router/src/test/router.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/src/test/router.test">;
}
declare module "@lugia/lugiax-router/target/interface/lugiax-router.flow.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax-router/target/interface/lugiax-router.flow"
  >;
}
declare module "@lugia/lugiax-router/target/lib/go.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/target/lib/go">;
}
declare module "@lugia/lugiax-router/target/lib/index.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/target/lib/index">;
}
declare module "@lugia/lugiax-router/target/lib/Link.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/target/lib/Link">;
}
declare module "@lugia/lugiax-router/target/lib/Loading.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/target/lib/Loading">;
}
declare module "@lugia/lugiax-router/target/lib/router.js" {
  declare module.exports: $Exports<"@lugia/lugiax-router/target/lib/router">;
}
