// flow-typed signature: 9c394751dd3f83c230e511a3bdf238c2
// flow-typed version: <<STUB>>/@lugia/lugiax_v^1.0.1-2.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/lugiax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/lugiax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/lugiax/src/interface/lugiax.flow' {
  declare module.exports: any;
}

declare module '@lugia/lugiax/target/interface/lugiax.flow' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/lugiax/src/interface/lugiax.flow.js' {
  declare module.exports: $Exports<"@lugia/lugiax/src/interface/lugiax.flow">;
}
declare module '@lugia/lugiax/target/interface/lugiax.flow.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax/target/interface/lugiax.flow"
  >;
}
